In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("texture.dat")
df.head()

      A1     A2     A3     A4     A5  ...    A37    A38    A39    A40   Class
0 -1.223 -0.798 -0.867 -0.639 -0.545  ... -0.871 -0.620 -0.568 -0.607       2
1 -1.410 -1.029 -1.013 -0.895 -0.762  ... -1.013 -0.748 -0.698 -0.817       2
2 -1.107 -0.649 -0.629 -0.492 -0.367  ... -0.746 -0.457 -0.379 -0.469       2
3 -1.270 -0.855 -0.958 -0.707 -0.619  ... -0.937 -0.693 -0.657 -0.779       2
4 -1.331 -0.862 -0.761 -0.689 -0.498  ... -0.952 -0.642 -0.578 -0.648       2

[5 rows x 41 columns]

In [8]:
#  стандартизация
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(df.iloc[:, :-1])
y = df[' Class']

In [25]:
from sklearn.decomposition import PCA

# метод главных компонент
pca = PCA()
pca.fit(X)

# критерий Кайзера
eig_values = pca.singular_values_
print(len(eig_values[eig_values > 1]))

37

In [30]:
pca = PCA(n_components=37)
pca.fit(X)
new_X = pca.transform(X)
new_X.shape

(5500, 37)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.4, random_state=42)

In [33]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score

# точность
accuracy_score(y_test, y_pred)

0.9104545454545454

Точность дерева > 91%, что являтся достаточно хорошим результатом